<a href="https://colab.research.google.com/github/ZichKoding/FCC-DataAnalysis.ipynb/blob/main/FCC_DataAnalysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Analysis with Python

## Broadcasting and Vectorized operations

In [ ]:
import numpy as np

a = np.arange(5)

In [ ]:
a

array([0, 1, 2, 3, 4])

In [ ]:
a + 10

array([10, 11, 12, 13, 14])

In [ ]:
a * 10

array([ 0, 10, 20, 30, 40])

In [ ]:
a

array([0, 1, 2, 3, 4])

In [ ]:
a += 100

In [ ]:
a

array([100, 101, 102, 103, 104])

In [ ]:
l = [0, 1, 2, 3]

In [ ]:
[i * 10 for i in l]

[0, 10, 20, 30]

In [ ]:
a = np.arange(4)

In [ ]:
a

array([0, 1, 2, 3])

In [ ]:
b = np.array([10, 10, 10, 10])

In [ ]:
a + b

array([10, 11, 12, 13])

In [ ]:
a * b

array([ 0, 10, 20, 30])

## Boolean Arrays

Set an array with a length of 4 and start with 0. 

In [ ]:
a = np.arange(4)

In [ ]:
a

array([0, 1, 2, 3])

This is looking for the first and last items in the array.

In [ ]:
a[[0, -1]]

array([0, 3])

Set the first and last values to true and the second and third values to false. This should mean don't return the second and third values. **_Note: This does not set a to equal these values. Notebook just shows you what it looks like. If you print(a) then you will see what a is._**

In [ ]:
a[[True, False, False, True]]

array([0, 3])

Broadcast `a >= 2 is` checking to see which values in the array are greater than or equal to the number two. As if-statements the value will only return true or false.

In [ ]:
a >= 2

array([False, False,  True,  True])

Enclosing `a >= 2` in brackets (vectorizing) of `a` then you will not receive True or False, but the actual items that are greater than or equal to two. 

In [ ]:
a[a >= 2]

array([2, 3])

In [ ]:
a.mean()

1.5

In [ ]:
a[a > a.mean()]

array([2, 3])

Find all elements that are ***not*** greater than the mean.

In [ ]:
a[~(a > a.mean())]

array([0, 1])

In [ ]:
a[(a == 0) | (a == 1)]

array([0, 1])

In [ ]:
a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

In [ ]:
A = np.random.randint(100, size=(3, 3))

In [ ]:
A

array([[14, 71, 43],
       [94, 20, 36],
       [92, 93,  4]])

In [ ]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

array([14, 43, 20, 92,  4])

In [ ]:
A > 30

array([[False,  True,  True],
       [ True, False,  True],
       [ True,  True, False]])

## Linear Algebra

In [ ]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [ ]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [ ]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [ ]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [ ]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [ ]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

## Size of objects in Memory

Int, floats

In [ ]:
import sys

# An integer in Python is 24 bytes
sys.getsizeof(1)

28

In [ ]:
# Longs are even larger
sys.getsizeof(10**100)

72

In [ ]:
# Numpy size is much smaller
np.dtype(int).itemsize

8

In [ ]:
np.dtype(float).itemsize

8

Lists are even larger

In [ ]:
# A one-element list
sys.getsizeof([1])

64

In [ ]:
# An array of one element in numpy 
np.array([1]).nbytes

8

And performance is also important

In [ ]:
l = list(range(10000))

In [ ]:
a = np.arange(10000)

In [ ]:
%time sum( [ x** 2 for x in l ] )

CPU times: user 3.43 ms, sys: 47 µs, total: 3.48 ms
Wall time: 3.52 ms


333283335000

In [ ]:
%time np.sum(a ** 2)

CPU times: user 651 µs, sys: 0 ns, total: 651 µs
Wall time: 657 µs


333283335000

## Intro to Pandas

In [ ]:
import pandas as pd
import numpy as np

### Panda series

We'll start analyzing "The Group of Seven". Which is a political formed by Canada, France, German, Italy, Japan, the United Kingdom, and the United States. We'll start by analyzing population, and for that, we'll use a `pandas.Series` object.

In [ ]:
# In millions
g7_pop = pd.Series([35.467, 63.951, 80.940, 60.665, 127.061, 64.511, 318.523])

In [ ]:
g7_pop

0     35.467
1     63.951
2     80.940
3     60.665
4    127.061
5     64.511
6    318.523
dtype: float64

Someone might not know we're representing population in millions of inhabitants. Series can have a `name`, to better document the purpose of the Serires:

In [ ]:
g7_pop.name = 'G7 Population in millions'

In [ ]:
g7_pop

0     35.467
1     63.951
2     80.940
3     60.665
4    127.061
5     64.511
6    318.523
Name: G7 Population in millions, dtype: float64

Series are pretty similar to numpy arrays:

In [ ]:
g7_pop.dtype

dtype('float64')

In [ ]:
g7_pop.values

array([ 35.467,  63.951,  80.94 ,  60.665, 127.061,  64.511, 318.523])

In [ ]:
type(g7_pop.values)

numpy.ndarray

In [ ]:
g7_pop[0]

35.467

In [ ]:
g7_pop[1]

63.951

In [ ]:
g7_pop.index

RangeIndex(start=0, stop=7, step=1)

But, in contrast to lists, we can explicitly define the index:

In [ ]:
g7_pop.index = [
    'Canada',
    'France',
    'Germany',
    'Italy',
    'Japan',
    'United Kingdom',
    'United States'
]

In [ ]:
g7_pop

Canada             35.467
France             63.951
Germany            80.940
Italy              60.665
Japan             127.061
United Kingdom     64.511
United States     318.523
Name: G7 Population in millions, dtype: float64

We can say that Series look like "ordered dictionaries". We can actually create a Series out of dictionaries:

In [ ]:
pd.Series({
    'Canada': 35.467,
    'France': 63.951,
    'Germany': 80.94,
    'Italy': 60.665,
    'Japan': 127.061,
    'United Kingdom': 64.511,
    'United States': 318.523
}, name='G7 Population in millions')

Canada             35.467
France             63.951
Germany            80.940
Italy              60.665
Japan             127.061
United Kingdom     64.511
United States     318.523
Name: G7 Population in millions, dtype: float64

In [ ]:
pd.Series(
    [35.467, 63.951, 80.94, 60.665, 127.061, 64.511, 318.523],
    index=['Canada', 'France', 'Germany', 'Italy', 'Japan', 'United Kingdom', 
           'United States'],
    name='G7 Population in millions'
)

Canada             35.467
France             63.951
Germany            80.940
Italy              60.665
Japan             127.061
United Kingdom     64.511
United States     318.523
Name: G7 Population in millions, dtype: float64

In [ ]:
pd.Series(g7_pop, index=['France', 'Germany', 'Italy', 'Spain'])

France     63.951
Germany    80.940
Italy      60.665
Spain         NaN
Name: G7 Population in millions, dtype: float64

### Indexing

Indexing works similarly to lists and dictionaries, you use the **index** of the element you are looking for:

In [ ]:
g7_pop

Canada             35.467
France             63.951
Germany            80.940
Italy              60.665
Japan             127.061
United Kingdom     64.511
United States     318.523
Name: G7 Population in millions, dtype: float64

In [ ]:
g7_pop['Canada']

35.467

In [ ]:
g7_pop['Canada']

35.467

In [ ]:
g7_pop['Japan']

127.061

Numeric positions can also be used, with `iloc` attribute:

In [ ]:
g7_pop.iloc[0]

35.467

In [ ]:
g7_pop.iloc[-1]

318.523

Selecting multiple elements at once:

(The result is another Series)

In [ ]:
g7_pop[['Italy', 'France']]

Italy     60.665
France    63.951
Name: G7 Population in millions, dtype: float64

In [ ]:
g7_pop.iloc[[0, 1]]

Canada    35.467
France    63.951
Name: G7 Population in millions, dtype: float64

In [ ]:
g7_pop['Canada': 'Italy']

Canada     35.467
France     63.951
Germany    80.940
Italy      60.665
Name: G7 Population in millions, dtype: float64

### Conditional selection (boolean arrays)

The same boolean array techniques we saw applied to numpy arrays can be used for Panda `Series`:

In [ ]:
g7_pop

Canada             35.467
France             63.951
Germany            80.940
Italy              60.665
Japan             127.061
United Kingdom     64.511
United States     318.523
Name: G7 Population in millions, dtype: float64

In [ ]:
g7_pop > 70

Canada            False
France            False
Germany            True
Italy             False
Japan              True
United Kingdom    False
United States      True
Name: G7 Population in millions, dtype: bool

In [ ]:
g7_pop[g7_pop > 70]

Germany           80.940
Japan            127.061
United States    318.523
Name: G7 Population in millions, dtype: float64

In [ ]:
g7_pop.mean()

107.30257142857144

In [ ]:
g7_pop[g7_pop > g7_pop.mean()]

Japan            127.061
United States    318.523
Name: G7 Population in millions, dtype: float64

In [ ]:
g7_pop.std()

97.24996987121581

In [ ]:
g7_pop[(g7_pop > g7_pop.mean() - g7_pop.std() / 2) | (g7_pop > g7_pop.mean() + g7_pop.std() / 2)]

France             63.951
Germany            80.940
Italy              60.665
Japan             127.061
United Kingdom     64.511
United States     318.523
Name: G7 Population in millions, dtype: float64

### Operations and methods

Series also support vectorized operatons and aggregation functions as Numpy:

In [ ]:
g7_pop

Canada             35.467
France             63.951
Germany            80.940
Italy              60.665
Japan             127.061
United Kingdom     64.511
United States     318.523
Name: G7 Population in millions, dtype: float64

In [ ]:
g7_pop * 1_000_000

Canada             35467000.0
France             63951000.0
Germany            80940000.0
Italy              60665000.0
Japan             127061000.0
United Kingdom     64511000.0
United States     318523000.0
Name: G7 Population in millions, dtype: float64

In [ ]:
g7_pop.mean()

107.30257142857144

In [ ]:
np.log(g7_pop)

Canada            3.568603
France            4.158117
Germany           4.393708
Italy             4.105367
Japan             4.844667
United Kingdom    4.166836
United States     5.763695
Name: G7 Population in millions, dtype: float64

In [ ]:
g7_pop['France': 'Italy'].mean()

68.51866666666666

### Boolean arrays

(Work in the same way as numpy)

In [ ]:
g7_pop

Canada             35.467
France             63.951
Germany            80.940
Italy              60.665
Japan             127.061
United Kingdom     64.511
United States     318.523
Name: G7 Population in millions, dtype: float64

In [ ]:
g7_pop > 80

Canada            False
France            False
Germany            True
Italy             False
Japan              True
United Kingdom    False
United States      True
Name: G7 Population in millions, dtype: bool

In [ ]:
g7_pop[g7_pop > 80]

Germany           80.940
Japan            127.061
United States    318.523
Name: G7 Population in millions, dtype: float64

In [ ]:
g7_pop[(g7_pop > 80) | (g7_pop < 40)]

Canada            35.467
Germany           80.940
Japan            127.061
United States    318.523
Name: G7 Population in millions, dtype: float64

In [ ]:
g7_pop[(g7_pop > 80) & (g7_pop < 200)]

Germany     80.940
Japan      127.061
Name: G7 Population in millions, dtype: float64

### Modifying series

In [ ]:
g7_pop['Canada'] = 40.5

In [ ]:
g7_pop

Canada             40.500
France             63.951
Germany            80.940
Italy              60.665
Japan             127.061
United Kingdom     64.511
United States     318.523
Name: G7 Population in millions, dtype: float64

In [ ]:
g7_pop.iloc[-1] = 500

In [ ]:
g7_pop

Canada             40.500
France             63.951
Germany            80.940
Italy              60.665
Japan             127.061
United Kingdom     64.511
United States     500.000
Name: G7 Population in millions, dtype: float64

In [ ]:
g7_pop[g7_pop < 70] = 99.99

In [ ]:
g7_pop

Canada             99.990
France             99.990
Germany            80.940
Italy              99.990
Japan             127.061
United Kingdom     99.990
United States     500.000
Name: G7 Population in millions, dtype: float64

### Pandas - Dataframes

Probably the most important data structure of pandas is the `DataFrame`. It's a tabular structure tightly integrated with `Series`. 

In [ ]:
import numpy as np
import pandas as pd

We'll keep our analysis of G7 countries and looking now at DataFrames. As said, a DataFrame looks a lot like a table.

Creating `DataFrame`s manually can be tedious. 99% of the time you'll be pulling the data from a Database, a csv file or the web. But still, you can create a DataFrame by specifying the columns and values:

In [ ]:
df = pd.DataFrame({
    'Population': [35.467, 63.951, 80.94, 60.665, 127.061, 64.511, 318.523],
    'GDP': [
        1785387,
        2833687,
        3874437,
        2167744,
        4602367,
        2950039,
        17348075
    ],
    'Surface Area': [
        9984670,
        640679,
        357114,
        301336,
        377930,
        242495,
        9525067
    ],
    'HDI': [
        0.913,
        0.888,
        0.916,
        0.873,
        0.891,
        0.907,
        0.915
    ],
    'Continent': [
        'America',
        'Europe',
        'Europe',
        'Europe',
        'Asia', 
        'Europe', 
        'America'
    ]
}, columns=['Population', 'GDP', 'Surface Area', 'HDI', 'Continent'])

*(The `columns` attribute is optional. I'm using it to keep the same order as in the picture above)*

In [ ]:
df

Population       GDP  Surface Area    HDI Continent
0      35.467   1785387       9984670  0.913   America
1      63.951   2833687        640679  0.888    Europe
2      80.940   3874437        357114  0.916    Europe
3      60.665   2167744        301336  0.873    Europe
4     127.061   4602367        377930  0.891      Asia
5      64.511   2950039        242495  0.907    Europe
6     318.523  17348075       9525067  0.915   America

`DataFrame`s also have indexes. As you can see in the "table" above, pandas has assigned a numeric, autoincremental index automatically to each "row" in our DataFrame. In our case, we know that each row represents a country, so we'll just reassign the index:

In [ ]:
df.index = [
    'Canada',
    'France', 
    'Germany', 
    'Italy', 
    'Japan', 
    'United Kingdom', 
    'United States'
]

In [ ]:
df

Population       GDP  Surface Area    HDI Continent
Canada              35.467   1785387       9984670  0.913   America
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Italy               60.665   2167744        301336  0.873    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

In [ ]:
df.columns

Index(['Population', 'GDP', 'Surface Area', 'HDI', 'Continent'], dtype='object')

In [ ]:
df.index

Index(['Canada', 'France', 'Germany', 'Italy', 'Japan', 'United Kingdom',
       'United States'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7 entries, Canada to United States
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Population    7 non-null      float64
 1   GDP           7 non-null      int64  
 2   Surface Area  7 non-null      int64  
 3   HDI           7 non-null      float64
 4   Continent     7 non-null      object 
dtypes: float64(2), int64(2), object(1)
memory usage: 336.0+ bytes


In [ ]:
df.size

35

In [ ]:
df.shape

(7, 5)

In [ ]:
df.describe()

Population           GDP  Surface Area       HDI
count    7.000000  7.000000e+00  7.000000e+00  7.000000
mean   107.302571  5.080248e+06  3.061327e+06  0.900429
std     97.249970  5.494020e+06  4.576187e+06  0.016592
min     35.467000  1.785387e+06  2.424950e+05  0.873000
25%     62.308000  2.500716e+06  3.292250e+05  0.889500
50%     64.511000  2.950039e+06  3.779300e+05  0.907000
75%    104.000500  4.238402e+06  5.082873e+06  0.914000
max    318.523000  1.734808e+07  9.984670e+06  0.916000

In [ ]:
df.dtypes

Population      float64
GDP               int64
Surface Area      int64
HDI             float64
Continent        object
dtype: object

In [ ]:
df.dtypes.value_counts()

float64    2
int64      2
object     1
dtype: int64

### Indexing, Selection and Slicing

Individual columns in the DataFrame can be selected with regular indexing. Each column is represented as a `Series`:

In [ ]:
df['Population']

Canada             35.467
France             63.951
Germany            80.940
Italy              60.665
Japan             127.061
United Kingdom     64.511
United States     318.523
Name: Population, dtype: float64

Note that the `index` of the returned Series is the same as the DataFrame one. And its `name` is the name of the column. If you're working on a notebook and want to see a more DataFrame-like format you can use the `to_frame` method:

In [ ]:
df['Population'].to_frame()

Population
Canada              35.467
France              63.951
Germany             80.940
Italy               60.665
Japan              127.061
United Kingdom      64.511
United States      318.523

Multiple columns can also be selected similarly to `numpy` and `Series`:

In [ ]:
df[['Population', 'GDP']]

Population       GDP
Canada              35.467   1785387
France              63.951   2833687
Germany             80.940   3874437
Italy               60.665   2167744
Japan              127.061   4602367
United Kingdom      64.511   2950039
United States      318.523  17348075

In this case, the result is another `DataFrame`. Slicing works differently, it acts at "row level", and can be counter intuitive:

In [ ]:
df[1:3]

Population      GDP  Surface Area    HDI Continent
France       63.951  2833687        640679  0.888    Europe
Germany      80.940  3874437        357114  0.916    Europe

Row level selection works better wih `loc` and `iloc` **which are recommended** over regular "direct slicing" (`df[:]`).

`loc` selects row matching the given index:

In [ ]:
df.loc['Italy']

Population       60.665
GDP             2167744
Surface Area     301336
HDI               0.873
Continent        Europe
Name: Italy, dtype: object

In [ ]:
df.loc['France': 'Italy']

Population      GDP  Surface Area    HDI Continent
France       63.951  2833687        640679  0.888    Europe
Germany      80.940  3874437        357114  0.916    Europe
Italy        60.665  2167744        301336  0.873    Europe

As a second "argument", you can pass the column(s) you'd like to select:

In [ ]:
df.loc['France': 'Italy', 'Population']

France     63.951
Germany    80.940
Italy      60.665
Name: Population, dtype: float64

In [ ]:
df.loc['France': 'Italy', ['Population', 'GDP']]

Population      GDP
France       63.951  2833687
Germany      80.940  3874437
Italy        60.665  2167744

In [ ]:
import pandas as pd

In [ ]:
certificates_earned = pd.DataFrame({
    'Certificates': [8, 2, 5, 6],
    'Time (in months)': [16, 5, 9, 12]
})

In [ ]:
certificates_earned.index = ['Tom', 'Kris', 'Ahmad', 'Beau']

In [ ]:
certificates_earned

Certificates  Time (in months)
Tom               8                16
Kris              2                 5
Ahmad             5                 9
Beau              6                12

In [ ]:
print(certificates_earned.iloc[2])

Certificates        5
Time (in months)    9
Name: Ahmad, dtype: int64


### Pandas Conditional Selection and Modifying DataFrames

We saw conditional selection applied to `Series` and it'll work in the same way for `DataFrame`s. After all, a `DataFrame` is a collection of `Series`:

In [ ]:
df

Population       GDP  Surface Area    HDI Continent
Canada              35.467   1785387       9984670  0.913   America
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Italy               60.665   2167744        301336  0.873    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

In [ ]:
df['Population'] > 70

Canada            False
France            False
Germany            True
Italy             False
Japan              True
United Kingdom    False
United States      True
Name: Population, dtype: bool

In [ ]:
df.loc[df['Population'] > 70]

Population       GDP  Surface Area    HDI Continent
Germany            80.940   3874437        357114  0.916    Europe
Japan             127.061   4602367        377930  0.891      Asia
United States     318.523  17348075       9525067  0.915   America

The boolean matchin is done at index level, so you can filter by any row, as long as it contains the right indexes. Column selection still works as expected:

In [ ]:
df.loc[df['Population'] > 70, ['Population', 'GDP']]

Population       GDP
Germany            80.940   3874437
Japan             127.061   4602367
United States     318.523  17348075

### Dropping stuff

Opposed to the concept of selection, we have "dropping". Instead of pointing out which values you'd like to select you could point which ones you'd like to `drop`:

In [ ]:
df

Population       GDP  Surface Area    HDI Continent
Canada              35.467   1785387       9984670  0.913   America
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Italy               60.665   2167744        301336  0.873    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

In [ ]:
df.drop('Canada')

Population       GDP  Surface Area    HDI Continent
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Italy               60.665   2167744        301336  0.873    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

In [ ]:
df.drop(['Canada', 'Japan'])

Population       GDP  Surface Area    HDI Continent
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Italy               60.665   2167744        301336  0.873    Europe
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

In [ ]:
df.drop(columns=['Population', 'HDI'])

GDP  Surface Area Continent
Canada           1785387       9984670   America
France           2833687        640679    Europe
Germany          3874437        357114    Europe
Italy            2167744        301336    Europe
Japan            4602367        377930      Asia
United Kingdom   2950039        242495    Europe
United States   17348075       9525067   America

In [ ]:
df.drop(["Italy", 'Canada'], axis=0)

Population       GDP  Surface Area    HDI Continent
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

In [ ]:
df.drop(['Population', 'HDI'], axis=1)

GDP  Surface Area Continent
Canada           1785387       9984670   America
France           2833687        640679    Europe
Germany          3874437        357114    Europe
Italy            2167744        301336    Europe
Japan            4602367        377930      Asia
United Kingdom   2950039        242495    Europe
United States   17348075       9525067   America

In [ ]:
df.drop(['Population', 'HDI'], axis=1)

GDP  Surface Area Continent
Canada           1785387       9984670   America
France           2833687        640679    Europe
Germany          3874437        357114    Europe
Italy            2167744        301336    Europe
Japan            4602367        377930      Asia
United Kingdom   2950039        242495    Europe
United States   17348075       9525067   America

In [ ]:
df.drop(['Population', 'HDI'], axis='columns')

GDP  Surface Area Continent
Canada           1785387       9984670   America
France           2833687        640679    Europe
Germany          3874437        357114    Europe
Italy            2167744        301336    Europe
Japan            4602367        377930      Asia
United Kingdom   2950039        242495    Europe
United States   17348075       9525067   America

In [ ]:
df.drop(['Canada', 'Germany'], axis='rows')

Population       GDP  Surface Area    HDI Continent
France              63.951   2833687        640679  0.888    Europe
Italy               60.665   2167744        301336  0.873    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

All these `drop` methods return a new `DataFrame`. If you'd like to modify it "in place", you can use the `inplace` attribute (there's 

### Operations

In [ ]:
df

Population       GDP  Surface Area    HDI Continent
Canada              35.467   1785387       9984670  0.913   America
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Italy               60.665   2167744        301336  0.873    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

In [ ]:
df[['Population', 'GDP']]

Population       GDP
Canada              35.467   1785387
France              63.951   2833687
Germany             80.940   3874437
Italy               60.665   2167744
Japan              127.061   4602367
United Kingdom      64.511   2950039
United States      318.523  17348075

In [ ]:
df[['Population', 'GDP']] / 100

Population        GDP
Canada             0.35467   17853.87
France             0.63951   28336.87
Germany            0.80940   38744.37
Italy              0.60665   21677.44
Japan              1.27061   46023.67
United Kingdom     0.64511   29500.39
United States      3.18523  173480.75

**Operations with Series** work at a column level, broadcasting down the rows (which can be counter intuitive). 

In [ ]:
crisis = pd.Series([-1_000_000, -0.3], index=['GDP', 'HDI'])

In [ ]:
df[['GDP', 'HDI']] + crisis

GDP    HDI
Canada            785387.0  0.613
France           1833687.0  0.588
Germany          2874437.0  0.616
Italy            1167744.0  0.573
Japan            3602367.0  0.591
United Kingdom   1950039.0  0.607
United States   16348075.0  0.615

### Modifying DataFrames

It's simple and ituitive, You can add columns, or replace values for columns without series:

#### Adding a new column

In [ ]:
langs = pd.Series(
    ['French', 'German', 'Italian'],
    index=['France', 'Germany', 'Italy'],
    name='Language'
)

In [ ]:
df['Language'] = langs

In [ ]:
df

Population       GDP  Surface Area    HDI Continent Language
Canada              35.467   1785387       9984670  0.913   America      NaN
France              63.951   2833687        640679  0.888    Europe   French
Germany             80.940   3874437        357114  0.916    Europe   German
Italy               60.665   2167744        301336  0.873    Europe  Italian
Japan              127.061   4602367        377930  0.891      Asia      NaN
United Kingdom      64.511   2950039        242495  0.907    Europe      NaN
United States      318.523  17348075       9525067  0.915   America      NaN

#### Replacing values per column

In [ ]:
df['Language'] = 'English'

In [ ]:
df

Population       GDP  Surface Area    HDI Continent Language
Canada              35.467   1785387       9984670  0.913   America  English
France              63.951   2833687        640679  0.888    Europe  English
Germany             80.940   3874437        357114  0.916    Europe  English
Italy               60.665   2167744        301336  0.873    Europe  English
Japan              127.061   4602367        377930  0.891      Asia  English
United Kingdom      64.511   2950039        242495  0.907    Europe  English
United States      318.523  17348075       9525067  0.915   America  English

#### Renaming Columns

In [ ]:
df.rename(
    columns={
        'HDI': 'Human Development Index',
        'Anual Popcorn Consumption': 'APC'
    }, index={
        'United States': 'USA',
        'United Kingdom': 'UK',
        'Argentina': 'AR'
    }
)

Population       GDP  Surface Area  Human Development Index  \
Canada       35.467   1785387       9984670                    0.913   
France       63.951   2833687        640679                    0.888   
Germany      80.940   3874437        357114                    0.916   
Italy        60.665   2167744        301336                    0.873   
Japan       127.061   4602367        377930                    0.891   
UK           64.511   2950039        242495                    0.907   
USA         318.523  17348075       9525067                    0.915   

        Continent Language  
Canada    America  English  
France     Europe  English  
Germany    Europe  English  
Italy      Europe  English  
Japan        Asia  English  
UK         Europe  English  
USA       America  English

In [ ]:
df.rename(index=str.upper)

Population       GDP  Surface Area    HDI Continent Language
CANADA              35.467   1785387       9984670  0.913   America  English
FRANCE              63.951   2833687        640679  0.888    Europe  English
GERMANY             80.940   3874437        357114  0.916    Europe  English
ITALY               60.665   2167744        301336  0.873    Europe  English
JAPAN              127.061   4602367        377930  0.891      Asia  English
UNITED KINGDOM      64.511   2950039        242495  0.907    Europe  English
UNITED STATES      318.523  17348075       9525067  0.915   America  English

In [ ]:
df.rename(index=lambda x: x.lower())

Population       GDP  Surface Area    HDI Continent Language
canada              35.467   1785387       9984670  0.913   America  English
france              63.951   2833687        640679  0.888    Europe  English
germany             80.940   3874437        357114  0.916    Europe  English
italy               60.665   2167744        301336  0.873    Europe  English
japan              127.061   4602367        377930  0.891      Asia  English
united kingdom      64.511   2950039        242495  0.907    Europe  English
united states      318.523  17348075       9525067  0.915   America  English

#### Dropping columns

In [ ]:
df

Population       GDP  Surface Area    HDI Continent Language
Canada              35.467   1785387       9984670  0.913   America  English
France              63.951   2833687        640679  0.888    Europe  English
Germany             80.940   3874437        357114  0.916    Europe  English
Italy               60.665   2167744        301336  0.873    Europe  English
Japan              127.061   4602367        377930  0.891      Asia  English
United Kingdom      64.511   2950039        242495  0.907    Europe  English
United States      318.523  17348075       9525067  0.915   America  English

In [ ]:
df.drop(columns='Language', inplace=True)

In [ ]:
df

Population       GDP  Surface Area    HDI Continent
Canada              35.467   1785387       9984670  0.913   America
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Italy               60.665   2167744        301336  0.873    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

In [ ]:
import pandas as pd

In [ ]:
certificates_earned = pd.DataFrame({
    'Certificates': [8, 2, 5, 6],
    'Time (in months)': [16, 5, 9, 12]
})

In [ ]:
certificates_earned

Certificates  Time (in months)
0             8                16
1             2                 5
2             5                 9
3             6                12

In [ ]:
names = ['Tom', 'Kris', 'Ahmad', 'Beau']

In [ ]:
certificates_earned.index = names

In [ ]:
certificates_earned

Certificates  Time (in months)
Tom               8                16
Kris              2                 5
Ahmad             5                 9
Beau              6                12

In [ ]:
longest_streak = pd.Series([13, 11, 9, 7], index=names)

In [ ]:
longest_streak

Tom      13
Kris     11
Ahmad     9
Beau      7
dtype: int64

In [ ]:
certificates_earned['Longest streak'] = longest_streak

In [ ]:
certificates_earned

Certificates  Time (in months)  Longest streak
Tom               8                16              13
Kris              2                 5              11
Ahmad             5                 9               9
Beau              6                12               7

#### Adding values

In [ ]:
df.append(pd.Series({
    'Population': 3, 
    'GDP': 5
}, name='China'))

Population         GDP  Surface Area    HDI Continent
Canada              35.467   1785387.0     9984670.0  0.913   America
France              63.951   2833687.0      640679.0  0.888    Europe
Germany             80.940   3874437.0      357114.0  0.916    Europe
Italy               60.665   2167744.0      301336.0  0.873    Europe
Japan              127.061   4602367.0      377930.0  0.891      Asia
United Kingdom      64.511   2950039.0      242495.0  0.907    Europe
United States      318.523  17348075.0     9525067.0  0.915   America
China                3.000         5.0           NaN    NaN       NaN

In [ ]:
df

Population       GDP  Surface Area    HDI Continent
Canada              35.467   1785387       9984670  0.913   America
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Italy               60.665   2167744        301336  0.873    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

You can directly set the new index and values to the `DataFrame`:

In [ ]:
df.loc['China'] = pd.Series({'Population': 1_400_000_000, 'Continent': 'Asian'})

In [ ]:
df

Population         GDP  Surface Area    HDI Continent
Canada          3.546700e+01   1785387.0     9984670.0  0.913   America
France          6.395100e+01   2833687.0      640679.0  0.888    Europe
Germany         8.094000e+01   3874437.0      357114.0  0.916    Europe
Italy           6.066500e+01   2167744.0      301336.0  0.873    Europe
Japan           1.270610e+02   4602367.0      377930.0  0.891      Asia
United Kingdom  6.451100e+01   2950039.0      242495.0  0.907    Europe
United States   3.185230e+02  17348075.0     9525067.0  0.915   America
China           1.400000e+09         NaN           NaN    NaN     Asian

We can use `drop` to just remove a row by index:

In [ ]:
df.drop('China', inplace=True)

In [ ]:
df

Population         GDP  Surface Area    HDI Continent
Canada              35.467   1785387.0     9984670.0  0.913   America
France              63.951   2833687.0      640679.0  0.888    Europe
Germany             80.940   3874437.0      357114.0  0.916    Europe
Italy               60.665   2167744.0      301336.0  0.873    Europe
Japan              127.061   4602367.0      377930.0  0.891      Asia
United Kingdom      64.511   2950039.0      242495.0  0.907    Europe
United States      318.523  17348075.0     9525067.0  0.915   America

#### More radical index changes

In [ ]:
df.reset_index()

index  Population         GDP  Surface Area    HDI Continent
0          Canada      35.467   1785387.0     9984670.0  0.913   America
1          France      63.951   2833687.0      640679.0  0.888    Europe
2         Germany      80.940   3874437.0      357114.0  0.916    Europe
3           Italy      60.665   2167744.0      301336.0  0.873    Europe
4           Japan     127.061   4602367.0      377930.0  0.891      Asia
5  United Kingdom      64.511   2950039.0      242495.0  0.907    Europe
6   United States     318.523  17348075.0     9525067.0  0.915   America

In [ ]:
df.set_index('Population')

GDP  Surface Area    HDI Continent
Population                                           
35.467       1785387.0     9984670.0  0.913   America
63.951       2833687.0      640679.0  0.888    Europe
80.940       3874437.0      357114.0  0.916    Europe
60.665       2167744.0      301336.0  0.873    Europe
127.061      4602367.0      377930.0  0.891      Asia
64.511       2950039.0      242495.0  0.907    Europe
318.523     17348075.0     9525067.0  0.915   America

### Pandas Creating Columns

#### Creating collumns from other columns

Altering a DataFrame often involves combining different columns into another. For example, in our Countries analysis, we could try to calculate the "GDP per capita", which is just, `GDP / Population`.

In [ ]:
df

Population         GDP  Surface Area    HDI Continent
Canada              35.467   1785387.0     9984670.0  0.913   America
France              63.951   2833687.0      640679.0  0.888    Europe
Germany             80.940   3874437.0      357114.0  0.916    Europe
Italy               60.665   2167744.0      301336.0  0.873    Europe
Japan              127.061   4602367.0      377930.0  0.891      Asia
United Kingdom      64.511   2950039.0      242495.0  0.907    Europe
United States      318.523  17348075.0     9525067.0  0.915   America

In [ ]:
df[['Population', 'GDP']]

Population         GDP
Canada              35.467   1785387.0
France              63.951   2833687.0
Germany             80.940   3874437.0
Italy               60.665   2167744.0
Japan              127.061   4602367.0
United Kingdom      64.511   2950039.0
United States      318.523  17348075.0

The regular pandas way of expressing that, is just dividing each series:

In [ ]:
df['GDP'] / df['Population']

Canada            50339.385908
France            44310.284437
Germany           47868.013343
Italy             35733.025633
Japan             36221.712406
United Kingdom    45729.239975
United States     54464.120330
dtype: float64

The result of that operation is just another series that you can add to the original `DataFrame`:

In [ ]:
df['GDP Per Capita'] = df['GDP'] / df['Population']

In [ ]:
df

Population         GDP  Surface Area    HDI Continent  \
Canada              35.467   1785387.0     9984670.0  0.913   America   
France              63.951   2833687.0      640679.0  0.888    Europe   
Germany             80.940   3874437.0      357114.0  0.916    Europe   
Italy               60.665   2167744.0      301336.0  0.873    Europe   
Japan              127.061   4602367.0      377930.0  0.891      Asia   
United Kingdom      64.511   2950039.0      242495.0  0.907    Europe   
United States      318.523  17348075.0     9525067.0  0.915   America   

                GDP Per Capita  
Canada            50339.385908  
France            44310.284437  
Germany           47868.013343  
Italy             35733.025633  
Japan             36221.712406  
United Kingdom    45729.239975  
United States     54464.120330

#### Statisitcal Info

You've already seen the `describe` method, which gives you a good "summary" of the `DataFrame`. Let's explore other methods in more detail:

In [ ]:
df

Population         GDP  Surface Area    HDI Continent  \
Canada              35.467   1785387.0     9984670.0  0.913   America   
France              63.951   2833687.0      640679.0  0.888    Europe   
Germany             80.940   3874437.0      357114.0  0.916    Europe   
Italy               60.665   2167744.0      301336.0  0.873    Europe   
Japan              127.061   4602367.0      377930.0  0.891      Asia   
United Kingdom      64.511   2950039.0      242495.0  0.907    Europe   
United States      318.523  17348075.0     9525067.0  0.915   America   

                GDP Per Capita  
Canada            50339.385908  
France            44310.284437  
Germany           47868.013343  
Italy             35733.025633  
Japan             36221.712406  
United Kingdom    45729.239975  
United States     54464.120330

In [ ]:
df.head()

Population        GDP  Surface Area    HDI Continent  GDP Per Capita
Canada       35.467  1785387.0     9984670.0  0.913   America    50339.385908
France       63.951  2833687.0      640679.0  0.888    Europe    44310.284437
Germany      80.940  3874437.0      357114.0  0.916    Europe    47868.013343
Italy        60.665  2167744.0      301336.0  0.873    Europe    35733.025633
Japan       127.061  4602367.0      377930.0  0.891      Asia    36221.712406

In [ ]:
df.describe()

Population           GDP  Surface Area       HDI  GDP Per Capita
count    7.000000  7.000000e+00  7.000000e+00  7.000000        7.000000
mean   107.302571  5.080248e+06  3.061327e+06  0.900429    44952.254576
std     97.249970  5.494020e+06  4.576187e+06  0.016592     6954.983875
min     35.467000  1.785387e+06  2.424950e+05  0.873000    35733.025633
25%     62.308000  2.500716e+06  3.292250e+05  0.889500    40265.998421
50%     64.511000  2.950039e+06  3.779300e+05  0.907000    45729.239975
75%    104.000500  4.238402e+06  5.082873e+06  0.914000    49103.699626
max    318.523000  1.734808e+07  9.984670e+06  0.916000    54464.120330

In [ ]:
population = df['Population']

In [ ]:
population

Canada             35.467
France             63.951
Germany            80.940
Italy              60.665
Japan             127.061
United Kingdom     64.511
United States     318.523
Name: Population, dtype: float64

In [ ]:
population.min(), population.max()

(35.467, 318.523)

In [ ]:
population.sum()

751.118

In [ ]:
population.sum()/ len(population)

107.30257142857144

In [ ]:
population.mean()

107.30257142857144

In [ ]:
population.std()

97.24996987121581

In [ ]:
population.median()

64.511

In [ ]:
population.describe()

count      7.000000
mean     107.302571
std       97.249970
min       35.467000
25%       62.308000
50%       64.511000
75%      104.000500
max      318.523000
Name: Population, dtype: float64

In [ ]:
population.quantile(.25)

62.308

In [ ]:
population.quantile([0.2, 0.4, 0.6, 0.8, 1])

0.2     61.3222
0.4     64.1750
0.6     74.3684
0.8    117.8368
1.0    318.5230
Name: Population, dtype: float64

### Reading external data & Plotting

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

%matplotlib inline

Pandas can easily read data stored in different file formats like CSV, JSON, XML, or even Excel. Parsing always involves specifying the correct structure, encoding and other details. The `read_csv` method reads CSV files and accepts many parameters. 

In [ ]:
pd.read_csv?

In [ ]:
df = pd.read_csv('data/btc-market-price.csv')

FileNotFoundError: ignored